/*
 Piwik - free/libre analytics platform

 JavaScript tracking client

 @link http://piwik.org
 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license http://piwik.org/free-software/bsd/ BSD-3 Clause (also in ./LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
 @license-end */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(l,k,n){l instanceof String&&(l=String(l));for(var v=l.length,p=0;p<v;p++){var J=l[p];if(k.call(n,J,p,l))return{i:p,v:J}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(l,k,n){if(l==Array.prototype||l==Object.prototype)return l;l[k]=n.value;return l};$jscomp.getGlobal=function(l){l=["object"==typeof globalThis&&globalThis,l,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<l.length;++k){var n=l[k];if(n&&n.Math==Math)return n}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(l,k){var n=$jscomp.propertyToPolyfillSymbol[k];if(null==n)return l[k];n=l[n];return void 0!==n?n:l[k]};
$jscomp.polyfill=function(l,k,n,v){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(l,k,n,v):$jscomp.polyfillUnisolated(l,k,n,v))};$jscomp.polyfillUnisolated=function(l,k,n,v){n=$jscomp.global;l=l.split(".");for(v=0;v<l.length-1;v++){var p=l[v];if(!(p in n))return;n=n[p]}l=l[l.length-1];v=n[l];k=k(v);k!=v&&null!=k&&$jscomp.defineProperty(n,l,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(l,k,n,v){var p=l.split(".");l=1===p.length;v=p[0];v=!l&&v in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var J=0;J<p.length-1;J++){var D=p[J];if(!(D in v))return;v=v[D]}p=p[p.length-1];n=$jscomp.IS_SYMBOL_NATIVE&&"es6"===n?v[p]:null;k=k(n);null!=k&&(l?$jscomp.defineProperty($jscomp.polyfills,p,{configurable:!0,writable:!0,value:k}):k!==n&&(void 0===$jscomp.propertyToPolyfillSymbol[p]&&(n=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[p]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(p):$jscomp.POLYFILL_PREFIX+n+"$"+p),$jscomp.defineProperty(v,$jscomp.propertyToPolyfillSymbol[p],{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("Array.prototype.find",function(l){return l?l:function(k,n){return $jscomp.findInternal(this,k,n).v}},"es6","es3");
Array.prototype.forEach||(Array.prototype.forEach=function(l,k){var n;if(null==this)throw new TypeError(" this is null or not defined");var v=Object(this),p=v.length>>>0;if("[object Function]"!={}.toString.call(l))throw new TypeError(l+" is not a function");k&&(n=k);for(k=0;k<p;){if(k in v){var J=v[k];l.call(n,J,k,v)}k++}});
var searchIntervalId=searchIntervalId||0,searchIntervalCount=searchIntervalId||0,DcmAn={addListener:function(l,k,n){l.addEventListener?l.addEventListener(k,n,{passive:!0}):l.attachEvent&&l.attachEvent("on"+k,n)},addFormEvent:function(){var l=document.getElementsByTagName("form");for(i=0;i<l.length;i++)DcmAn.addListener(l[i],"submit",DcmAn.decorateMe)},addEvent:function(){var l=document.getElementsByTagName("a");for(i=0;i<l.length;i++)DcmAn.addListener(l[i],"mousedown",DcmAn.decorateMe),DcmAn.addListener(l[i],
"keyup",DcmAn.decorateMe),DcmAn.addListener(l[i],"touchstart",DcmAn.decorateMe)},decorateMe:function(l){l=l||window.event;if((l=l.target||l.srcElement)&&l.href)DcmAn.checkDomain(l.href)&&(l.href=DcmAn.decorateDmpfCross(l.href));else if(l&&l.action&&DcmAn.checkDomain(l.action))if("get"==l.method){var k=DcmAn.getDaCookieId();if(1<k.length){var n=document.createElement("input");n.type="hidden";n.name="dcmancr";n.value=DcmAn.makeCrossParam(k);l.appendChild(n)}}else l.action=DcmAn.decorateDmpfCross(l.action)},
checkDomain:function(l){var k=!1;_dcmlinker.forEach(function(n){var v=l.match(/^https?:\/\/([^\/:]+)/);null!=v&&v[1]==n&&(k=!0)});return k},decorateDmpfCross:function(l){var k=DcmAn.getDaCookieId();if(1<k.length){var n=l.split("#");l=n[0];k=DcmAn.makeCrossParam(k);var v=l.split("?");if(1==v.length)l=l+"?dcmancr="+k;else{v=v[1].split("&");var p=!0;for(i=0;i<v.length;i++)if(0==v[i].indexOf("dcmancr=")){p=!1;break}p&&(l=l+"&dcmancr="+k)}1<n.length&&(l=l+"#"+n[1])}return l},makeCrossParam:function(l){for(var k=
l.length,n=0,v=(new Date).getTime(),p=0;p<k;p++)n+=l.charCodeAt(p);k=DcmAn.getGaCookieId();p=DcmAn.makeUa();return l+"."+v+"."+p+"."+(n+v+p)+(k?"_"+k+"_"+Piwik.getAsyncTracker().getSiteId():"")},getDaCookieId:function(){if(window.navigator.cookieEnabled&&document.cookie)for(var l=document.cookie.split("; "),k=0;k<l.length;k++){var n=l[k].split("=");if(-1<n[0].indexOf("_pk_id."+Piwik.getAsyncTracker().getSiteId()+"."))return n[1].split(".")[0]}return""},getGaCookieId:function(){if(window.navigator.cookieEnabled&&
document.cookie){var l=/(^|;)[ ]*_ga=([^;]*)/.exec(document.cookie);if((l=l?l[2]:"")&&l.match(/.*\.\d+\.(\d+\.\d+)/))return RegExp.$1}return 0},makeUa:function(){for(var l=navigator.userAgent.length,k=0,n=0;n<l;n++)k+=navigator.userAgent.charCodeAt(n);return k}};"object"!==typeof JSON2&&(JSON2=window.JSON||{});
(function(){function l(z){if("undefined"!=typeof window.addEventListener){var K=document.readyState;"interactive"==K||"complete"==K||"loaded"==K?z():document.addEventListener("DOMContentLoaded",z,!1)}else"undefined"!=typeof window.attachEvent&&(window.attachEvent("onload",z),z())}function k(z){return 10>z?"0"+z:z}function n(z){ma.lastIndex=0;return ma.test(z)?'"'+z.replace(ma,function(K){var V=cb[K];return"string"===typeof V?V:"\\u"+("0000"+K.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+z+'"'}
function v(z,K){var V=W,A=K[z];if(A&&"object"===typeof A){var da=Object.prototype.toString.apply(A);A="[object Date]"===da?isFinite(A.valueOf())?A.getUTCFullYear()+"-"+k(A.getUTCMonth()+1)+"-"+k(A.getUTCDate())+"T"+k(A.getUTCHours())+":"+k(A.getUTCMinutes())+":"+k(A.getUTCSeconds())+"Z":null:"[object String]"===da||"[object Number]"===da||"[object Boolean]"===da?A.valueOf():"[object Array]"!==da&&"function"===typeof A.toJSON?A.toJSON(z):A}"function"===typeof aa&&(A=aa.call(K,z,A));switch(typeof A){case "string":return n(A);
case "number":return isFinite(A)?String(A):"null";case "boolean":case "null":return String(A);case "object":if(!A)return"null";W+=Ha;var T=[];if("[object Array]"===Object.prototype.toString.apply(A)){da=A.length;for(z=0;z<da;z+=1)T[z]=v(z,A)||"null";K=0===T.length?"[]":W?"[\n"+W+T.join(",\n"+W)+"\n"+V+"]":"["+T.join(",")+"]";W=V;return K}if(aa&&"object"===typeof aa)for(da=aa.length,z=0;z<da;z+=1){if("string"===typeof aa[z]){var M=aa[z];(K=v(M,A))&&T.push(n(M)+(W?": ":":")+K)}}else for(M in A)Object.prototype.hasOwnProperty.call(A,
M)&&(K=v(M,A))&&T.push(n(M)+(W?": ":":")+K);K=0===T.length?"{}":W?"{\n"+W+T.join(",\n"+W)+"\n"+V+"}":"{"+T.join(",")+"}";W=V;return K}}l(DcmAn.addEvent);l(DcmAn.addFormEvent);var p="",J=location.href,D=J.split("?dcmancr=");2==D.length?p=-1!=D[1].indexOf("&")?D[1].split("&")[0]:D[1]:(D=J.split("&dcmancr="),2==D.length&&(p=-1!=D[1].indexOf("&")?D[1].split("&")[0]:D[1]));0<p.length&&12E4>(new Date).getTime()-p.split(".")[1]&&(p=p.split("_"),_paq.unshift(["appendToTrackingUrl","dcmancr="+p[0]]));"use strict";
var na=/[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,ma=/[\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,W,Ha,cb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},aa;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(z,K,V){var A;Ha=W="";if("number"===typeof V)for(A=0;A<V;A+=1)Ha+=" ";else"string"===typeof V&&(Ha=V);if((aa=
K)&&"function"!==typeof K&&("object"!==typeof K||"number"!==typeof K.length))throw Error("JSON2.stringify");return v("",{"":z})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(z,K){function V(A,da){var T,M=A[da];if(M&&"object"===typeof M)for(T in M)if(Object.prototype.hasOwnProperty.call(M,T)){var Qa=V(M,T);void 0!==Qa?M[T]=Qa:delete M[T]}return K.call(A,da,M)}z=String(z);na.lastIndex=0;na.test(z)&&(z=z.replace(na,function(A){return"\\u"+("0000"+A.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(z.replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return z=eval("("+z+")"),"function"===typeof K?V({"":z},""):z;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function l(b){try{return qb(b)}catch(e){return unescape(b)}}function k(b){return"undefined"!==typeof b}function n(b){return"function"===typeof b}function v(b){return"object"===typeof b}function p(b){return"string"===typeof b||b instanceof String}function J(){var b;for(b=0;b<arguments.length;b+=1){var e=arguments[b];var f=e.shift();p(f)?db[f].apply(db,e):f.apply(db,e)}}function D(b,e,f,g){if(b.addEventListener)return b.addEventListener(e,f,g),!0;if(b.attachEvent)return b.attachEvent("on"+
e,f);b["on"+e]=f}function na(b,e){var f="",g;for(g in Ra)if(Object.prototype.hasOwnProperty.call(Ra,g)){var r=Ra[g][b];n(r)&&(f+=r(e))}return f}function ma(){var b;if(!Sa)for(Sa=!0,na("load"),b=0;b<rb.length;b++)rb[b]();return!0}function W(b,e){var f=w.createElement("script");f.type="text/javascript";f.src=b;f.readyState?f.onreadystatechange=function(){var g=this.readyState;if("loaded"===g||"complete"===g)f.onreadystatechange=null,e()}:f.onload=e;w.getElementsByTagName("head")[0].appendChild(f)}function Ha(){var b=
"";try{b=x.top.document.referrer}catch(e){if(x.parent)try{b=x.parent.document.referrer}catch(f){b=""}}""===b&&(b=w.referrer);return b}function cb(b){return(b=/^([a-z]+):/.exec(b))?b[1]:null}function aa(b){var e=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(b);return e?e[1]:b}function z(b,e){return(b=(new RegExp("[\\?&#]"+e+"=([^&#]*)")).exec(b))?qb(b[1]):""}function K(b){var e=function(Aa,oa){return Aa<<oa|Aa>>>32-oa},f=function(Aa){var oa="",Ba;for(Ba=7;0<=Ba;Ba--){var Ta=Aa>>>4*Ba&15;oa+=Ta.toString(16)}return oa},
g,r=[],R=1732584193,N=4023233417,O=2562383102,ba=271733878,ia=3285377520,F=[];b=xc(E(b));var C=b.length;for(g=0;g<C-3;g+=4){var B=b.charCodeAt(g)<<24|b.charCodeAt(g+1)<<16|b.charCodeAt(g+2)<<8|b.charCodeAt(g+3);F.push(B)}switch(C&3){case 0:g=2147483648;break;case 1:g=b.charCodeAt(C-1)<<24|8388608;break;case 2:g=b.charCodeAt(C-2)<<24|b.charCodeAt(C-1)<<16|32768;break;case 3:g=b.charCodeAt(C-3)<<24|b.charCodeAt(C-2)<<16|b.charCodeAt(C-1)<<8|128}for(F.push(g);14!==(F.length&15);)F.push(0);F.push(C>>>
29);F.push(C<<3&4294967295);for(b=0;b<F.length;b+=16){for(g=0;16>g;g++)r[g]=F[b+g];for(g=16;79>=g;g++)r[g]=e(r[g-3]^r[g-8]^r[g-14]^r[g-16],1);B=R;C=N;var X=O;var U=ba;var ja=ia;for(g=0;19>=g;g++){var L=e(B,5)+(C&X|~C&U)+ja+r[g]+1518500249&4294967295;ja=U;U=X;X=e(C,30);C=B;B=L}for(g=20;39>=g;g++)L=e(B,5)+(C^X^U)+ja+r[g]+1859775393&4294967295,ja=U,U=X,X=e(C,30),C=B,B=L;for(g=40;59>=g;g++)L=e(B,5)+(C&X|C&U|X&U)+ja+r[g]+2400959708&4294967295,ja=U,U=X,X=e(C,30),C=B,B=L;for(g=60;79>=g;g++)L=e(B,5)+(C^X^
U)+ja+r[g]+3395469782&4294967295,ja=U,U=X,X=e(C,30),C=B,B=L;R=R+B&4294967295;N=N+C&4294967295;O=O+X&4294967295;ba=ba+U&4294967295;ia=ia+ja&4294967295}L=f(R)+f(N)+f(O)+f(ba)+f(ia);return L.toLowerCase()}function V(b,e,f){if("translate.googleusercontent.com"===b)""===f&&(f=e),e=z(e,"u"),b=aa(e);else if("cc.bingj.com"===b||"webcache.googleusercontent.com"===b||"74.6."===b.slice(0,5))e=w.links[0].href,b=aa(e);return[b,e,f]}function A(b){var e=b.length;"."===b.charAt(--e)&&(b=b.slice(0,e));"*."===b.slice(0,
2)&&(b=b.slice(1));return b}function da(b){b=b&&b.text?b.text:b;if(!p(b)){var e=w.getElementsByTagName("title");e&&k(e[0])&&(b=e[0].text)}return b}function T(b){return b?!k(b.children)&&k(b.childNodes)||k(b.children)?b.children:[]:[]}function M(b,e){if(b&&b.indexOf)return b.indexOf(e);if(!k(b)||null===b||!b.length)return-1;var f=b.length;if(0===f)return-1;for(var g=0;g<f;){if(b[g]===e)return g;g++}return-1}function Qa(b){function e(g,r){if(x.getComputedStyle)return w.defaultView.getComputedStyle(g,
null)[r];if(g.currentStyle)return g.currentStyle[r]}function f(g,r,R,N,O,ba,ia){var F=g.parentNode,C;a:{for(C=g.parentNode;C;){if(C===w){C=!0;break a}C=C.parentNode}C=!1}if(!C)return!1;if(9===F.nodeType)return!0;if("0"===e(g,"opacity")||"none"===e(g,"display")||"hidden"===e(g,"visibility"))return!1;k(r)&&k(R)&&k(N)&&k(O)&&k(ba)&&k(ia)||(r=g.offsetTop,O=g.offsetLeft,N=r+g.offsetHeight,R=O+g.offsetWidth,ba=g.offsetWidth,ia=g.offsetHeight);if(b===g&&(0===ia||0===ba)&&"hidden"===e(g,"overflow"))return!1;
if(F){if("hidden"===e(F,"overflow")||"scroll"===e(F,"overflow"))if(O+1>F.offsetWidth+F.scrollLeft||O+ba-1<F.scrollLeft||r+1>F.offsetHeight+F.scrollTop||r+ia-1<F.scrollTop)return!1;g.offsetParent===F&&(O+=F.offsetLeft,r+=F.offsetTop);return f(F,r,R,N,O,ba,ia)}return!0}return b?f(b):!1}function yc(b,e){if(e)return e;"piwik.php"===b.slice(-9)&&(b=b.slice(0,b.length-9));return b}function Ca(b){var e=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(w.referrer);
if(e){if(e[1]!==String(b))return!1;x.name="Piwik_Overlay###"+e[2]+"###"+e[3]}b=x.name.split("###");return 3===b.length&&"Piwik_Overlay"===b[0]}function zc(b,e,f){var g=x.name.split("###"),r=g[1],R=g[2],N=yc(b,e);W(N+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(N,f,r,R)})}function Nb(b,e){function f(a,c,d,h,m,t){if(!ua){if(d){var q=new Date;q.setTime(q.getTime()+d)}try{if(0<=a.indexOf("_pk_id")&&c.split(".")[0]){localStorage.setItem("_pk_id",E(c.split(".")[0]));
for(var H=H||[],y=document.cookie.split("; "),G=0;G<y.length;G++){var P=y[G].split("=");if(P[0]&&-1<P[0].indexOf("_pk_id.")&&P[1]){var ea=P[1].split(".");if(ea&&ea[0]&&c.split(".")[0]&&(H.push(ea[0]),ea[0]!=c.split(".")[0])){var Ia=P[1].replace(ea[0],c.split(".")[0]);w.cookie=P[0]+"="+E(Ia)+(d?";expires="+q.toGMTString():"")+";path="+(h||"/")+(m?";domain="+m:"")+(t?";secure":"")}}}if(H&&0<H.length){y="";localStorage.getItem("_pk_id")&&(y=Ja(localStorage.getItem("_pk_id"))+".");P=!1;for(G=0;G<H.length;G++)y=
y+H[G]+".",H[G]!=Ja(localStorage.getItem("_pk_id"))&&(P=!0);if(P){var S=(-1<Z.indexOf("dcm-analytics.com")?"https://dev.dcm-analytics.com":"https://docomo-analytics.com")+"/dcm/cookie/associate?idsite="+Q+"&cookieAssociate="+y,la=document.createElement("img");la.setAttribute("src",S);la.style.display="none";document.body.appendChild(la)}}}}catch(pa){}w.cookie=a+"="+E(c)+(d?";expires="+q.toGMTString():"")+";path="+(h||"/")+(m?";domain="+m:"")+(t?";secure":"")}}function g(a){return ua?0:(a=(new RegExp("(^|;)[ ]*"+
a+"=([^;]*)")).exec(w.cookie))?qb(a[2]):0}function r(a){if(Ob){var c=/#.*/;return a.replace(c,"")}return a}function R(a){var c;for(c=0;c<eb.length;c++){var d=A(eb[c].toLowerCase());if(a===d)return!0;if("."===d.slice(0,1)){if(a===d.slice(1))return!0;var h=a.length-d.length;if(0<h&&a.slice(h)===d)return!0}}return!1}function N(a,c){c=!0;a=Z+(0>Z.indexOf("?")?"?":"&")+a;var d=Ka("daReqProb");if(null==d||0==(new Date).getTime()%d){null!=Ka("afterAuthFlg")&&(a+="&afterAuthFlg=1");if(1==Ka("trackingType"))if(null!=
Ka("afterAuthFlg"))if(d=Ja(localStorage.getItem("dcmsend")),!d||d<(new Date).getTime()){a+="&trackingType=1";d=(new Date).getTime();try{localStorage.setItem("dcmsend",(new Date(d+4752E5)).getTime())}catch(h){d=B("dcmsend"),0===g(d)?(a+="&trackingType=1",f(d,1,4752E5,"/")):c=!1}}else c=!1;else c=!1;else 2==Ka("trackingType")&&(a+="&trackingType=2");c&&(0>a.indexOf("&afterAuthFlg=1")&&window.navigator.cookieEnabled&&(c=Ja(localStorage.getItem("dcmunioncook")))&&c>(new Date).getTime()&&(a+="&afterAuthFlg=1"),
c=document.createElement("img"),c.setAttribute("src",a),c.style.display="none",document.body.appendChild(c))}}function O(a,c,d){console.log("sendXmlHttpRequest");k(d)&&null!==d||(d=!0);try{var h=x.XMLHttpRequest?new x.XMLHttpRequest:x.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;h.open("POST",Z,!0);h.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!d?"function"===typeof c&&c():N(a,c)};h.setRequestHeader("Content-Type",Pb);h.send(a)}catch(m){d&&N(a,
c)}}function ba(a){a=(new Date).getTime()+a;if(!Ua||a>Ua)Ua=a}function ia(a){var c=(new Date).getTime();La&&c<La?(c=La-c,setTimeout(a,c),ba(c+50),La+=50):(!1===La&&(La=c+800),a())}function F(a,c,d){!fb&&a&&ia(function(){"POST"===Qb?O(a,d):N(a,d);ba(c)})}function C(a,c){var d=fb?!1:a&&a.length;if(d){var h='{"requests":["?'+a.join('","?')+'"]}';ia(function(){O(h,null,!1);ba(c)})}}function B(a){return Rb+a+"."+Q+"."+Sb}function X(){if(ua)return"0";if(!k(fa.cookieEnabled)){var a=B("testcookie");f(a,"1");
return"1"===g(a)?"1":"0"}return fa.cookieEnabled?"1":"0"}function U(){Sb=sb((va||tb)+(wa||"/")).slice(0,4)}function ja(){var a=B("cvar");a=g(a);return a.length&&(a=JSON2.parse(a),v(a))?a:{}}function L(){ub=(new Date).getTime()}function Aa(){var a=Math.round((new Date).getTime()/1E3),c=B("id");return(c=g(c))?(a=c.split("."),a.unshift("0"),Va.length&&(a[1]=Va),a):a=["1",Va.length?Va:"0"===X()?"":sb((fa.userAgent||"")+(fa.platform||"")+JSON2.stringify(sa)+(new Date).getTime()+Math.random()).slice(0,
16),a,0,a,"",""]}function oa(){var a=Aa(),c=a[0],d=a[1],h=a[2]?a[2]:a[4],m=a[3]?a[3]:1,t=a[4],q="undefined"==a[5]||""==a[5]?a[4]:a[5];k(a[6])||(a[6]="");return{newVisitor:c,uuid:d,createTs:h,visitCount:m,currentVisitTs:t,lastVisitTs:q,lastEcommerceOrderTs:a[6]}}function Ba(){var a=(new Date).getTime(),c=oa().createTs;return 1E3*parseInt(c,10)+vb-a}function Ta(a){Q&&((new Date).getTime(),k(a)||(a=oa()),a=(localStorage.getItem("_pk_id")?Ja(localStorage.getItem("_pk_id")):a.uuid)+"."+a.createTs+".",
f(B("id"),a,Ba(),wa,va))}function Ma(){var a=g(B("ref"));if(a.length)try{if(a=JSON2.parse(a),v(a))return a}catch(c){}return["","",0,""]}function Wa(a,c,d){f(a,"",-86400,c,d);0<=a.indexOf("_pk_id")&&localStorage.removeItem("_pk_id")}function Tb(){var a=ua;ua=!1;Wa(B("id"),wa,va);Wa(B("ses"),wa,va);Wa(B("cvar"),wa,va);Wa(B("ref"),wa,va);ua=a}function Ub(a){if(a&&v(a)){var c=[];for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&c.push(d);var d={};c.sort();var h=c.length,m;for(m=0;m<h;m++)d[c[m]]=
a[c[m]];return d}}function qa(a,c,d,h){function m(Xa,Ac){Xa=JSON2.stringify(Xa);return 2<Xa.length?"&"+Ac+"="+E(Xa):""}var t=new Date,q=Math.round(t.getTime()/1E3),H=ha;var y=B("ses");B("ref");var G=B("cvar");var P=g(y);var ea=Ma();var Ia=gb||Vb;ua&&Tb();if(fb)return"";var S=oa();k(h)||(h="");var la={};var pa=location.search.substring(1).split("&");for(y=0;pa[y];y++){var ta=pa[y].split("=");la[ta[0]]=ta[1]}if(la.dcmancr){S.uuid=la.dcmancr.split(".")[0];try{localStorage.setItem("_pk_id",la.dcmancr.split(".")[0])}catch(Xa){}}var Ya=
w.characterSet||w.charset;Ya&&"utf-8"!==Ya.toLowerCase()||(Ya=null);ta=ea[0];var Za=ea[1];la=ea[2];pa=ea[3];if(!P){P=wb/1E3;if(!S.lastVisitTs||q-S.lastVisitTs>P)S.visitCount++,S.lastVisitTs=S.currentVisitTs;if(!xb||!ta.length){for(y in hb)if(Object.prototype.hasOwnProperty.call(hb,y)&&(ta=z(Ia,hb[y]),ta.length))break;for(y in ib)if(Object.prototype.hasOwnProperty.call(ib,y)&&(Za=z(Ia,ib[y]),Za.length))break}P=aa(Da);ea=pa.length?aa(pa):"";!P.length||R(P)||xb&&ea.length&&!R(ea)||(pa=Da);if(pa.length||
ta.length)la=q,ea=[ta,Za,la,r(pa.slice(0,1024))]}q=!1;1===Ka("trackingType")&&(q=!0);if(q)a="idsite="+Q+"&url="+E(r(Ia))+(Da.length?"&urlref="+E(r(Da)):"")+"&_id="+S.uuid;else{a+="&idsite="+Q+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+t.getHours()+"&m="+t.getMinutes()+"&s="+t.getSeconds()+"&url="+E(r(Ia))+(Da.length?"&urlref="+E(r(Da)):"")+(Na&&Na.length?"&uid="+E(Na):"")+"&_id="+S.uuid+"&_idts="+S.createTs+"&_idvc="+S.visitCount+"&_idn="+S.newVisitor+(ta.length?"&_rcn="+E(ta):"")+(Za.length?
"&_rck="+E(Za):"")+"&_refts="+la+"&_viewts="+S.lastVisitTs+(String(S.lastEcommerceOrderTs).length?"&_ects="+S.lastEcommerceOrderTs:"")+(String(pa).length?"&_ref="+E(r(pa.slice(0,1024))):"")+(Ya?"&cs="+E(Ya):"")+"&send_image=0";for(y in sa)Object.prototype.hasOwnProperty.call(sa,y)&&(a+="&"+y+"="+sa[y]);c?a+="&data="+E(JSON2.stringify(c)):xa&&(a+="&data="+E(JSON2.stringify(xa)));c=Ub(Ea);t=Ub(yb);a+=m(c,"cvar");a+=m(t,"e_cvar");if(ha){a+=m(ha,"_cvar");for(y in H)Object.prototype.hasOwnProperty.call(H,
y)&&(""===ha[y][0]||""===ha[y][1])&&delete ha[y];Wb&&f(G,JSON2.stringify(ha),wb,wa,va)}Xb&&(zb?a+="&gt_ms="+zb:Oa&&Oa.timing&&Oa.timing.requestStart&&Oa.timing.responseEnd&&(a+="&gt_ms="+(Oa.timing.responseEnd-Oa.timing.requestStart)))}S.lastEcommerceOrderTs=k(h)&&String(h).length?h:S.lastEcommerceOrderTs;Ta(S);a+=na(d);Ab.length&&(a+="&"+Ab);n(Bb)&&(a=Bb(a));if(window.navigator.cookieEnabled&&document.cookie)for(d=document.cookie.split("; "),y=0;y<d.length;y++)d[y].split("=")[0].split(".");return a}
function Yb(a,c,d,h,m,t){var q="idgoal=0",H=new Date,y=[],G;if(String(a).length){q+="&ec_id="+E(a);var P=Math.round(H.getTime()/1E3)}q+="&revenue="+c;String(d).length&&(q+="&ec_st="+d);String(h).length&&(q+="&ec_tx="+h);String(m).length&&(q+="&ec_sh="+m);String(t).length&&(q+="&ec_dt="+t);if(ca){for(G in ca)Object.prototype.hasOwnProperty.call(ca,G)&&(k(ca[G][1])||(ca[G][1]=""),k(ca[G][2])||(ca[G][2]=""),k(ca[G][3])&&0!==String(ca[G][3]).length||(ca[G][3]=0),k(ca[G][4])&&0!==String(ca[G][4]).length||
(ca[G][4]=1),y.push(ca[G]));q+="&ec_items="+E(JSON2.stringify(y))}q=qa(q,xa,"ecommerce",P);F(q,Y)}function Bc(a,c){var d=new Date;a=qa("action_name="+E(da(a||Zb)),c,"log");F(a,Y);Cb&&$a&&!$b&&($b=!0,D(w,"click",L),D(w,"mouseup",L),D(w,"mousedown",L),D(w,"mousemove",L),D(w,"mousewheel",L),D(x,"DOMMouseScroll",L),D(x,"scroll",L),D(w,"keypress",L),D(w,"keydown",L),D(w,"keyup",L),D(x,"resize",L),D(x,"focus",L),D(x,"blur",L),ub=d.getTime(),setTimeout(function m(){d=new Date;if(ub+$a>d.getTime()){if(Cb<
d.getTime()){var t=qa("ping=1",c,"ping");F(t,Y)}setTimeout(m,$a)}},$a))}function Db(a,c){var d="(^| )(piwik[_-]"+c;if(a)for(c=0;c<a.length;c++)d+="|"+a[c];return new RegExp(d+")( |$)")}function ab(a){return Z&&a&&0===String(a).indexOf(Z)}function Eb(a){var c=a,d;for(d=c.parentNode;null!==d&&k(d)&&!u.isLinkElement(c);)c=d,d=c.parentNode;a=c;if(u.hasNodeAttribute(a,"href")&&k(a.href)&&(c=u.getAttributeValueFromNode(a,"href"),!ab(c))){c=a.hostname||aa(a.href);var h=c.toLowerCase();c=a.href.replace(c,
h);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(c)){d=a.className;h=R(h);a=u.hasNodeAttribute(a,"download");if(ab(c))d=0;else{var m=Db(ac,"download"),t=Db(bc,"link"),q=new RegExp("\\.("+ya.join("|")+")([?&#]|$)","i");d=t.test(d)?"link":a||m.test(d)||q.test(c)?"download":h?0:"link"}if(d)return{type:d,href:c}}}}function bb(a,c,d,h){if(a=I.buildInteractionRequestParams(a,c,d,h))return qa(a,null,"contentInteraction")}function cc(a,c,d,h,m){if(k(a)){if(ab(a))return a;
var t=I.toAbsoluteUrl(a);t="redirecturl="+E(t)+"&";t+=bb(c,d,h,m||a);a="&";0>Z.indexOf("?")&&(a="?");return Z+a+t}}function Fb(a,c){if(!a||!c)return!1;var d=I.findTargetNode(a);if(I.shouldIgnoreInteraction(d))return!1;if(a=d=I.findTargetNodeNoDefault(a))a=!(d&&c&&(d.contains?d.contains(c):d===c||d.compareDocumentPosition&&d.compareDocumentPosition(c)&16));return a?!1:!0}function dc(a,c,d){if(a){var h=I.findParentContentNode(a);if(h&&Fb(h,a)&&(a=I.buildContentBlock(h)))return!a.target&&d&&(a.target=
d),I.buildInteractionRequestParams(c,a.name,a.piece,a.target)}}function ec(a){if(!za||!za.length)return!1;var c,d;for(c=0;c<za.length;c++)if((d=za[c])&&d.name===a.name&&d.piece===a.piece&&d.target===a.target)return!0;return!1}function Gb(a){if(!a)return!1;var c=I.findTargetNode(a);if(!c||I.shouldIgnoreInteraction(c))return!1;var d=Eb(c);if(Hb&&d&&d.type)return!1;if(u.isLinkElement(c)&&u.hasNodeAttributeWithValue(c,"href")){d=String(u.getAttributeValueFromNode(c,"href"));if(0===d.indexOf("#"))return!1;
if(ab(d))return!0;if(!I.isUrlToCurrentDomain(d))return!1;var h=I.buildContentBlock(a);if(!h)return;a=h.name;var m=h.piece;h=h.target;if(!u.hasNodeAttributeWithValue(c,I.CONTENT_TARGET_ATTR)||c.wasContentTargetAttrReplaced)c.wasContentTargetAttrReplaced=!0,h=I.toAbsoluteUrl(d),u.setAnyAttribute(c,I.CONTENT_TARGET_ATTR,h);d=cc(d,"click",a,m,h);I.setHrefAttribute(c,d);return!0}return!1}function fc(a){return function(c){if(a){var d=I.findParentContentNode(a),h;c&&(h=c.target||c.srcElement);h||(h=a);if(Fb(d,
h)){ba(Y);u.isLinkElement(a)&&u.hasNodeAttributeWithValue(a,"href")&&u.hasNodeAttributeWithValue(a,I.CONTENT_TARGET_ATTR)&&(c=u.getAttributeValueFromNode(a,"href"),!ab(c)&&a.wasContentTargetAttrReplaced&&u.setAnyAttribute(a,I.CONTENT_TARGET_ATTR,""));c=Eb(a);if(jb&&c&&c.type)return c.type;if(Gb(d))return"href";if(d=I.buildContentBlock(d))return d=bb("click",d.name,d.piece,d.target),F(d,Y),d}}}}function gc(a){if(a&&a.length){var c,d;for(c=0;c<a.length;c++)(d=I.findTargetNode(a[c]))&&!d.contentInteractionTrackingSetupDone&&
(d.contentInteractionTrackingSetupDone=!0,D(d,"click",fc(d)))}}function hc(a,c){if(!a||!a.length)return[];var d;for(d=0;d<a.length;d++)ec(a[d])?(a.splice(d,1),d--):za.push(a[d]);if(!a||!a.length)return[];if(c&&c.length)for(d=0;d<c.length;d++)Gb(c[d]);gc(c);var h=[];for(d=0;d<a.length;d++)c=qa(I.buildImpressionRequestParams(a[d].name,a[d].piece,a[d].target),void 0,"contentImpressions"),h.push(c);return h}function kb(a){var c=I.collectContent(a);return hc(c,a)}function Ib(a){if(!a||!a.length)return[];
var c;for(c=0;c<a.length;c++)I.isNodeVisible(a[c])||(a.splice(c,1),c--);return a&&a.length?kb(a):[]}function ic(a,c,d){a=I.buildImpressionRequestParams(a,c,d);return qa(a,null,"contentImpression")}function jc(a,c){if(a&&(a=I.findParentContentNode(a),a=I.buildContentBlock(a)))return c||(c="Unknown"),bb(c,a.name,a.piece,a.target)}function kc(a,c,d,h,m){if(0===String(a).length||0===String(c).length)return!1;a="e_c="+E(a)+"&e_a="+E(c)+(k(d)?"&e_n="+E(d):"")+(k(h)?"&e_v="+E(h):"");m=qa(a,m,"event");F(m,
Y)}function lc(a,c,d,h,m){c=c+"="+E(r(a));(a=dc(m,"click",a))&&(c+="&"+a);d=qa(c,d,"link");F(d,h?0:Y,h)}function mc(a,c){return""!==a?a+c.charAt(0).toUpperCase()+c.slice(1):c}function ka(a){var c,d,h=["","webkit","ms","moz"];if(!nc)for(d=0;d<h.length;d++){var m=h[d];if(Object.prototype.hasOwnProperty.call(w,mc(m,"hidden"))){"prerender"===w[mc(m,"visibilityState")]&&(c=!0);break}}c?D(w,m+"visibilitychange",function q(){w.removeEventListener(m+"visibilitychange",q,!1);a()}):a()}function lb(a){"complete"===
w.readyState?a():x.addEventListener?x.addEventListener("load",a):x.attachEvent&&x.attachEvent("onLoad",a)}function Jb(a){(w.attachEvent?"complete"===w.readyState:"loading"!==w.readyState)?a():w.addEventListener?w.addEventListener("DOMContentLoaded",a):w.attachEvent&&w.attachEvent("onreadystatechange",a)}function oc(a){var c=Eb(a);c&&c.type&&(c.href=l(c.href),lc(c.href,c.type,void 0,null,a))}function Kb(a){a=a||x.event;var c=a.which||a.button;var d=a.target||a.srcElement;"click"===a.type?d&&oc(d):
"mousedown"===a.type?1!==c&&2!==c||!d?mb=nb=null:(mb=c,nb=d):"mouseup"===a.type&&(c===mb&&d===nb&&oc(d),mb=nb=null)}function pc(a,c){c?(D(a,"mouseup",Kb,!1),D(a,"mousedown",Kb,!1)):D(a,"click",Kb,!1)}function qc(a){if(!jb){jb=!0;var c,d=Db(rc,"ignore"),h=w.links;if(h)for(c=0;c<h.length;c++)d.test(h[c].className)||pc(h[c],a)}}function sc(a,c,d){function h(){m=!0}if(Pa)return!0;Pa=!0;var m=!1,t,q;lb(function(){function H(G){setTimeout(function(){Pa&&(m=!1,d.trackVisibleContentImpressions(),H(G))},G)}
function y(G){setTimeout(function(){Pa&&(m&&(m=!1,d.trackVisibleContentImpressions()),y(G))},G)}if(a){t=["scroll","resize"];for(q=0;q<t.length;q++)w.addEventListener?w.addEventListener(t[q],h):x.attachEvent("on"+t[q],h);y(100)}c&&0<c&&(c=parseInt(c,10),H(c))})}function Ka(a){if("undefined"!=typeof _paq&&null!=_paq&&0<_paq.length){var c=null;_paq.forEach(function(d){d[0]===a&&(c=2==d.length?d[1]:d[0])});return c}return null}function Ja(a){return a?(a=a.replace(/</g,""),a=a.replace(/>/g,""),a=a.replace(/"/g,
""),a=a.replace(/'/g,""),a=a.replace(/&/g,"")):a}var ob={},Lb=V(w.domain,x.location.href,Ha()),tb=A(Lb[0]),Vb=l(Lb[1]),Da=l(Lb[2]),tc=!1,Qb="GET",Pb="application/x-www-form-urlencoded; charset=UTF-8",Z=b||"",uc="",Ab="",Q=e||"",Na="",Va="",gb,Zb=w.title,ya="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),
eb=[tb],rc=[],ac=[],bc=[],Y=500,Cb,$a,Ob,xa,hb=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],ib=["pk_kwd","piwik_kwd","utm_term"],Rb="_pk_",va,wa,ua=!1,fb,nc,xb,vb=339552E5,wb=18E5,Xb=!0,zb=0,Wb=!1,ha=!1,Bb,Ea={},yb={},ca={},sa={},za=[],Pa=!1,La=!1,jb=!1,Hb=!1,$b=!1,ub,mb,nb,sb=K,Sb;(function(){var a,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",
java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},d=/Mac OS X.*Safari\//.test(fa.userAgent)?x.devicePixelRatio||1:1;if(!/MSIE/.test(fa.userAgent)){if(fa.mimeTypes&&fa.mimeTypes.length)for(a in c)if(Object.prototype.hasOwnProperty.call(c,a)){var h=fa.mimeTypes[c[a]];sa[a]=h&&h.enabledPlugin?"1":"0"}"unknown"!==typeof navigator.javaEnabled&&k(fa.javaEnabled)&&fa.javaEnabled()&&(sa.java="1");n(x.GearsFactory)&&(sa.gears="1");sa.cookie=X()}sa.res=vc.width*
d+"x"+vc.height*d})();U();Ta();na("run",function(a,c){var d=null;if(p(a)&&!k(ob[a])&&c){if(v(c))d=c;else if(p(c))try{eval("hookObj ="+c)}catch(h){}ob[a]=d}return d});return{hook:ob,getHook:function(a){return ob[a]},getQuery:function(){return u},getContent:function(){return I},buildContentImpressionRequest:ic,buildContentInteractionRequest:bb,buildContentInteractionRequestNode:jc,buildContentInteractionTrackingRedirectUrl:cc,getContentImpressionsRequestsFromNodes:kb,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:Ib,
trackCallbackOnLoad:lb,trackCallbackOnReady:Jb,buildContentImpressionsRequests:hc,wasContentImpressionAlreadyTracked:ec,appendContentInteractionToRequestIfPossible:dc,setupInteractionsTracking:gc,trackContentImpressionClickInteraction:fc,internalIsNodeVisible:Qa,isNodeAuthorizedToTriggerInteraction:Fb,replaceHrefIfInternalLink:Gb,getConfigDownloadExtensions:function(){return ya},enableTrackOnlyVisibleContent:function(a,c){return sc(a,c,this)},clearTrackedContentImpressions:function(){za=[]},getTrackedContentImpressions:function(){return za},
clearEnableTrackOnlyVisibleContent:function(){Pa=!1},disableLinkTracking:function(){Hb=jb=!1},getConfigVisitorCookieTimeout:function(){return vb},getRemainingVisitorCookieTimeout:Ba,afterAuthFlg:function(a){if(1===a&&window.navigator.cookieEnabled&&((a=Ja(localStorage.getItem("dcmunioncook")))||a<(new Date).getTime())){a=(new Date).getTime();try{localStorage.setItem("dcmunioncook",(new Date(a+36E5)).getTime())}catch(m){var c=0;if(document.cookie)for(var d=document.cookie.split("; "),h=0;h<d.length;h++)if("dcmunioncook"===
d[h].split("=")[0]){c=1;break}0===c&&(a=(new Date(a+36E5)).toGMTString(),a="dcmunioncook="+escape(1)+"; expires="+a+"; path=/",document.cookie=a)}}},trackingType:function(a){if((1==a||2==a)&&"function"===typeof dcmganCallback){a=dcmganCallback;var c={};c.uid=oa().uuid;a(c)}},daReqProb:function(a){},gaCallbackTimeout:function(a){clearTimeout(a)},getVisitorId:function(){return oa().uuid},getVisitorInfo:function(){return Aa()},getAttributionInfo:function(){return Ma()},getAttributionCampaignName:function(){return Ma()[0]},
getAttributionCampaignKeyword:function(){return Ma()[1]},getAttributionReferrerTimestamp:function(){return Ma()[2]},getAttributionReferrerUrl:function(){return Ma()[3]},setTrackerUrl:function(a){Z=a},getTrackerUrl:function(){return Z},getSiteId:function(){return Q},setSiteId:function(a){Q=a;Ta()},setUserId:function(a){k(a)&&a.length&&(Na=a,Va=sb(Na).substr(0,16))},getUserId:function(){return Na},setCustomData:function(a,c){v(a)?xa=a:(xa||(xa={}),xa[a]=c)},getCustomData:function(){return xa},setCustomRequestProcessing:function(a){Bb=
a},appendToTrackingUrl:function(a){Ab=a},getRequest:function(a){return qa(a)},addPlugin:function(a,c){Ra[a]=c},setCustomVariable:function(a,c,d,h){k(h)||(h="visit");k(c)&&(k(d)||(d=""),0<a&&(c=p(c)?c:String(c),d=p(d)?d:String(d),c=[c.slice(0,200),d.slice(0,200)],"visit"===h||2===h?(!1===ha&&(ha=ja()),ha[a]=c):"page"===h||3===h?Ea[a]=c:"event"===h&&(yb[a]=c)))},getCustomVariable:function(a,c){k(c)||(c="visit");if("page"===c||3===c)var d=Ea[a];else if("event"===c)d=yb[a];else if("visit"===c||2===c)!1===
ha&&(ha=ja()),d=ha[a];return!k(d)||d&&""===d[0]?!1:d},deleteCustomVariable:function(a,c){this.getCustomVariable(a,c)&&this.setCustomVariable(a,"","",c)},storeCustomVariablesInCookie:function(){Wb=!0},setLinkTrackingTimer:function(a){Y=a},setDownloadExtensions:function(a){p(a)&&(a=a.split("|"));ya=a},addDownloadExtensions:function(a){var c;p(a)&&(a=a.split("|"));for(c=0;c<a.length;c++)ya.push(a[c])},removeDownloadExtensions:function(a){var c,d=[];p(a)&&(a=a.split("|"));for(c=0;c<ya.length;c++)-1===
M(a,ya[c])&&d.push(ya[c]);ya=d},setDomains:function(a){eb=p(a)?[a]:a;eb.push(tb)},setIgnoreClasses:function(a){rc=p(a)?[a]:a},setRequestMethod:function(a){Qb=a||"GET"},setRequestContentType:function(a){Pb=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){Da=a},setCustomUrl:function(a){var c=Vb;if(cb(a))gb=a;else if("/"===a.slice(0,1))gb=cb(c)+"://"+aa(c)+a;else{c=r(c);var d=c.indexOf("?");0<=d&&(c=c.slice(0,d));d=c.lastIndexOf("/");d!==c.length-1&&(c=c.slice(0,d+1));
gb=c+a}},setDocumentTitle:function(a){Zb=a},setAPIUrl:function(a){uc=a},setDownloadClasses:function(a){ac=p(a)?[a]:a},setLinkClasses:function(a){bc=p(a)?[a]:a},setCampaignNameKey:function(a){hb=p(a)?[a]:a},setCampaignKeywordKey:function(a){ib=p(a)?[a]:a},discardHashTag:function(a){Ob=a},setCookieNamePrefix:function(a){Rb=a;ha=ja()},setCookieDomain:function(a){a=A(a);f("test","testvalue",1E4,null,a);if("testvalue"===g("test")){Wa("test",null,a);var c=!0}else c=!1;c&&(va=a,U())},setCookiePath:function(a){wa=
a;U()},setVisitorCookieTimeout:function(a){vb=1E3*a},setSessionCookieTimeout:function(a){wb=1E3*a},setReferralCookieTimeout:function(a){},setConversionAttributionFirstReferrer:function(a){xb=a},disableCookies:function(){ua=!0;sa.cookie="0"},deleteCookies:function(){Tb()},setDoNotTrack:function(a){var c=fa.doNotTrack||fa.msDoNotTrack;(fb=a&&("yes"===c||"1"===c))&&this.disableCookies()},addListener:function(a,c){pc(a,c)},enableLinkTracking:function(a){Hb=!0;Sa?qc(a):rb.push(function(){qc(a)})},enableJSErrorTracking:function(){if(!tc){tc=
!0;var a=x.onerror;x.onerror=function(c,d,h,m,t){ka(function(){var q=d+":"+h;m&&(q+=":"+m);kc("JavaScript Errors",q,c)});return a?a(c,d,h,m,t):!1}}},disablePerformanceTracking:function(){Xb=!1},setGenerationTimeMs:function(a){zb=parseInt(a,10)},setHeartBeatTimer:function(a,c){Cb=(new Date).getTime()+1E3*a;$a=1E3*c},killFrame:function(){x.location!==x.top.location&&(x.top.location=x.location)},redirectFile:function(a){"file:"===x.location.protocol&&(x.location=a)},setCountPreRendered:function(a){nc=
a},trackGoal:function(a,c,d){ka(function(){var h=qa("idgoal="+a+(c?"&revenue="+c:""),d,"goal");F(h,Y)})},trackLink:function(a,c,d,h){ka(function(){lc(a,c,d,h)})},trackPageView:function(a,c){za=[];Ca(Q)?ka(function(){zc(Z,uc,Q)}):ka(function(){Bc(a,c)})},trackAllContentImpressions:function(){Ca(Q)||ka(function(){Jb(function(){var a=I.findContentNodes();a=kb(a);C(a,Y)})})},trackVisibleContentImpressions:function(a,c){Ca(Q)||(k(a)||(a=!0),k(c)||(c=750),sc(a,c,this),ka(function(){lb(function(){var d=
I.findContentNodes();d=Ib(d);C(d,Y)})}))},trackContentImpression:function(a,c,d){!Ca(Q)&&a&&(c=c||"Unknown",ka(function(){var h=ic(a,c,d);F(h,Y)}))},trackContentImpressionsWithinNode:function(a){!Ca(Q)&&a&&ka(function(){Pa?lb(function(){var c=I.findContentNodesWithinNode(a);c=Ib(c);C(c,Y)}):Jb(function(){var c=I.findContentNodesWithinNode(a);c=kb(c);C(c,Y)})})},trackContentInteraction:function(a,c,d,h){!Ca(Q)&&a&&c&&(d=d||"Unknown",ka(function(){var m=bb(a,c,d,h);F(m,Y)}))},trackContentInteractionNode:function(a,
c){!Ca(Q)&&a&&ka(function(){var d=jc(a,c);F(d,Y)})},trackEvent:function(a,c,d,h){ka(function(){kc(a,c,d,h)})},trackSiteSearch:function(a,c,d){ka(function(){var h=qa("search="+E(a)+(c?"&search_cat="+E(c):"")+(k(d)?"&search_count="+d:""),void 0,"sitesearch");F(h,Y)})},setEcommerceView:function(a,c,d,h){k(d)&&d.length?d instanceof Array&&(d=JSON2.stringify(d)):d="";Ea[5]=["_pkc",d];k(h)&&String(h).length&&(Ea[2]=["_pkp",h]);if(k(a)&&a.length||k(c)&&c.length)k(a)&&a.length&&(Ea[3]=["_pks",a]),k(c)&&c.length||
(c=""),Ea[4]=["_pkn",c]},addEcommerceItem:function(a,c,d,h,m){a.length&&(ca[a]=[a,c,d,h,m])},trackEcommerceOrder:function(a,c,d,h,m,t){String(a).length&&k(c)&&Yb(a,c,d,h,m,t)},trackEcommerceCartUpdate:function(a){k(a)&&Yb("",a,"","","","")},diPiNK:function(a){if(window.navigator.cookieEnabled&&Fa("dcmdipink")&&(null==a||0==(new Date).getTime()%a)){var c=g(B("id"));if(c){c=c.split(".")[0];var d=document.createElement("img");d.style.display="none";a="https:"==document.location.protocol?"https://":"http://";
d.src=a+"sync.im-apps.net/imid/set?cid=6094&tid=did&uid="+c;document.body.appendChild(d);c=document.createElement("iframe");a="https:"==document.location.protocol?"https://":"http://";c.src=a+"cf.im-apps.net/imid/beacon.html";c.style.display="none";document.body.appendChild(c);Ga("dcmdipink",864E5)}}},dcmsyfl:function(a){if(window.navigator.cookieEnabled&&Fa("dcmsyfl")&&!(null==a||0>=a||0!=(new Date).getTime()%a)){var c=g(B("id"));if(c){c=c.split(".")[0];a="/dcm/"+(-1<Z.indexOf("dcm-analytics.com")?
"t/":"")+"index.php";c="?idsite="+Q+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+c;var d=document.createElement("img");d.setAttribute("src","//cs.adingo.jp"+a+c);d.style.display="none";document.body.appendChild(d);Ga("dcmsyfl",4752E5)}}},dcmsydc:function(a){if(window.navigator.cookieEnabled&&Fa("dcmsydc")&&!(null==a||0>=a||0!=(new Date).getTime()%a)&&(a=g(B("id")))){a=a.split(".")[0];a="&idsite="+Q+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+a;var c=
document.createElement("img");c.setAttribute("src","//cm.g.doubleclick.net/pixel?google_nid=dmc_dmp&google_cm&google_sc"+a);c.style.display="none";document.body.appendChild(c);Ga("dcmsydc",4752E5)}},dcmsyal:function(a){if(window.navigator.cookieEnabled&&Fa("dcmsyal")&&!(null==a||0>=a||0!=(new Date).getTime()%a)&&(a=g(B("id")))){a=a.split(".")[0];var c="idsite="+Q,d="url="+E(document.location.protocol+"//"+document.domain);a="?"+c+"&"+d+"&dauid="+a+"&custom=a";c=document.createElement("img");c.setAttribute("src",
"//www.aolp.jp/ums/00/sync.php"+a);c.style.display="none";document.body.appendChild(c);Ga("dcmsyal",2592E6)}},dcmsyhk:function(a){if(window.navigator.cookieEnabled&&Fa("dcmsyhk")&&!(null==a||0>=a||0!=(new Date).getTime()%a)&&(a=g(B("id")))){a=a.split(".")[0];var c=-1<Z.indexOf("dcm-analytics.com")?"//sy.dcm-analytics.com":"//sy.docomo-analytics.com";a="?oid=207d81ffda0cc019&rdr="+E(c+"/dcm/sy/hk/?idsite="+(Q+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+a+"&uid={AONEID}"));c=
document.createElement("img");c.setAttribute("src","//aw.dw.impact-ad.jp/c/u/"+a);c.style.display="none";document.body.appendChild(c);Ga("dcmsyhk",2592E6)}},dcmsytd:function(a){if(Fa("dcmsytd")){var c=g(B("id"));!function(d,h){if(void 0===h[d]){h[d]=function(){h[d].clients.push(this);this._init=[Array.prototype.slice.call(arguments)]};h[d].clients=[];for(var m=function(y){return function(){return this["_"+y]=this["_"+y]||[],this["_"+y].push(Array.prototype.slice.call(arguments)),this}},t="addRecord set trackEvent trackPageview trackClicks ready".split(" "),
q=0;q<t.length;q++){var H=t[q];h[d].prototype[H]=m(H)}m=document.createElement("script");m.type="text/javascript";m.async=!0;m.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.treasuredata.com/sdk/1.9.2/td.min.js";t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(m,t)}}("Treasure",this);setTimeout(function(){if("undefined"!==typeof Treasure){var d=new Treasure({host:"tokyo.in.treasuredata.com",writeKey:"78/ea63175029cfec22348a9e4205cd2bdffe70e3a8",database:"dasynch"});
d.set("$global","td_global_id","td_global_id");c&&d.set("$global","cookie_id",c.split(".")[0]);d.trackPageview("dadatasynch",function(){d.fetchGlobalID(h)});var h=function(){if(window.navigator.cookieEnabled&&document.cookie){for(var m="",t=document.cookie.split("; "),q=0;q<t.length;q++){var H=t[q].split("=");-1<H[0].indexOf("_td_global")&&"null"!==H[1]&&(m=H[1])}if(m){if(null==a||0>=a||0!=(new Date).getTime()%a)return;c&&(c=c.split(".")[0],t=-1<Z.indexOf("dcm-analytics.com")?"//sy.dcm-analytics.com":
"//sy.docomo-analytics.com",m="?idsite="+Q+"&url="+(document.location.protocol+"//"+document.domain)+"&dauid="+c+"&uid="+m,q=document.createElement("img"),q.setAttribute("src",t+"/dcm/sy/td/"+m),q.style.display="none",document.body.appendChild(q))}Ga("dcmsytd",2592E6)}}}},500)}},dcmsyyh:function(a){if(window.navigator.cookieEnabled&&Fa("dcmsyyh")&&!(null==a||0>=a||0!=(new Date).getTime()%a)&&(a=g(B("id")))){a=a.split(".")[0];var c="idsite="+Q,d="url="+E(document.location.protocol+"//"+document.domain);
a="?"+c+"&"+d+"&dauid="+a+"&partner_id=NTTD&gdpr=false&euconsent=";c=document.createElement("img");c.setAttribute("src","//cms.analytics.yahoo.com/cms"+a);c.style.display="none";document.body.appendChild(c);Ga("dcmsyyh",2592E6)}},cvv:function(a){var c=(-1<Z.indexOf("dcm-analytics.com")?"//devcv.dcm-analytics.com":"//cv.docomo-analytics.com")+"/dcm/coll/cv/";g(B("id"))&&(g(B("id")),a+="&da_id="+g(B("id")).split(".")[0]);var d=document.createElement("img");d.setAttribute("src",c+(-1<a.indexOf("?")?
a:"?"+a));d.style.display="none";document.body.appendChild(d)},cvc:function(a,c){var d=(-1<Z.indexOf("dcm-analytics.com")?"//devcv.dcm-analytics.com":"//cv.docomo-analytics.com")+"/dcm/coll/cv/",h=document.getElementById(a);if(h){g(B("id"))&&(g(B("id")),c+="&cookie_id="+g(B("id")).split(".")[0]);var m=h.href;h.onclick=function(t){c=c.replace(/&dcm_z=[0-9]{13}/,"");c+="&dcm_z="+(new Date).getTime();var q=new XMLHttpRequest,H=t.button;t.which||void 0===H||(t.which=H&1?1:H&2?3:H&4?2:0);if(!(0!==t.button&&
1!==t.which||t.altKey||t.ctrlKey||t.shiftKey||t.metaKey||"_blank"==h.target||"_new"==h.target)){t.preventDefault();q.onreadystatechange=function(){2==q.readyState&&(null!=y&&(clearTimeout(y),y=null),window.location.href=m)};var y=setTimeout(function(){window.location.href=m},1E3)}q.open("GET",d+(-1<c.indexOf("?")?c:"?"+c));q.withCredentials=!0;q.send()}}},gaEvent:function(a,c,d){if(!(0<searchIntervalCount)&&a&&c&&(d=d?d:"_ga",window.navigator.cookieEnabled&&document.cookie)){for(var h=0,m=document.cookie.split("; "),
t=0;t<m.length;t++)if("dcmGaEv"===m[t].split("=")[0]){h=1;break}h||0!=searchIntervalId||(searchIntervalId=setInterval(function(){a:{var q=g(B("id")),H=d;if(0==q||0==q.split(".").length)clearInterval(searchIntervalId);else{for(var y=document.cookie.split("; "),G=0;G<y.length;G++){var P=y[G].split("=");if(P[0]===H&&4==P[1].split(".").length){clearInterval(searchIntervalId);H={};H["dimension"+c]=q.split(".")[0];H.nonInteraction=1;ga("create",a,"auto");ga("send","event",H);q=(new Date).getTime();q="dcmGaEv=1; expires="+
(new Date(q+31536E6)).toGMTString()+"; path=/";document.cookie=q;break a}}4<=searchIntervalCount?(clearInterval(searchIntervalId),searchIntervalCount=0):searchIntervalCount++}}},1E3))}}}}function Fa(b){var e=localStorage.getItem(b);if(e&&e>(new Date).getTime())return!1;e=document.cookie.split("; ");for(var f=0;f<e.length;f++)if(-1<e[f].split("=")[0].indexOf(b))return!1;return!0}function Ga(b,e){var f=(new Date).getTime(),g=(new Date(f+e)).getTime();try{localStorage.setItem(b,g)}catch(r){e=(new Date(f+
e)).toGMTString(),b=b+"="+escape(1)+"; expires="+e+"; path=/",document.cookie=b}}var Ua,Ra={},w=document,fa=navigator,vc=screen,x=window,Oa=x.performance||x.mozPerformance||x.msPerformance||x.webkitPerformance,Sa=!1,rb=[],E=x.encodeURIComponent,qb=x.decodeURIComponent,xc=unescape,ra,u={htmlCollectionToArray:function(b){var e=[],f;if(!b||!b.length)return e;for(f=0;f<b.length;f++)e.push(b[f]);return e},find:function(b){if(!document.querySelectorAll||!b)return[];b=document.querySelectorAll(b);return this.htmlCollectionToArray(b)},
findMultiple:function(b){if(!b||!b.length)return[];var e,f=[];for(e=0;e<b.length;e++){var g=this.find(b[e]);f=f.concat(g)}return f=this.makeNodesUnique(f)},findNodesByTagName:function(b,e){if(!b||!e||!b.getElementsByTagName)return[];b=b.getElementsByTagName(e);return this.htmlCollectionToArray(b)},makeNodesUnique:function(b){var e=[].concat(b);b.sort(function(N,O){if(N===O)return 0;N=M(e,N);O=M(e,O);return N===O?0:N>O?-1:1});if(1>=b.length)return b;var f=0,g=0,r=[],R;for(R=b[f++];R;)R===b[f]&&(g=
r.push(f)),R=b[f++]||null;for(;g--;)b.splice(r[g],1);return b},getAttributeValueFromNode:function(b,e){if(this.hasNodeAttribute(b,e)){if(b&&b.getAttribute)return b.getAttribute(e);if(b&&b.attributes&&"undefined"!==typeof b.attributes[e]){if(b.attributes[e].value)return b.attributes[e].value;if(b.attributes[e].nodeValue)return b.attributes[e].nodeValue;var f=b.attributes;if(f){for(b=0;b<f.length;b++)if(f[b].nodeName===e)return f[b].nodeValue;return null}}}},hasNodeAttributeWithValue:function(b,e){return!!this.getAttributeValueFromNode(b,
e)},hasNodeAttribute:function(b,e){return b&&b.hasAttribute?b.hasAttribute(e):b&&b.attributes?"undefined"!==typeof b.attributes[e]:!1},hasNodeCssClass:function(b,e){return b&&e&&b.className&&(b=b.className.split(" "),-1!==M(b,e))?!0:!1},findNodesHavingAttribute:function(b,e,f){f||(f=[]);if(!b||!e)return f;b=T(b);if(!b||!b.length)return f;var g;for(g=0;g<b.length;g++){var r=b[g];this.hasNodeAttribute(r,e)&&f.push(r);f=this.findNodesHavingAttribute(r,e,f)}return f},findFirstNodeHavingAttribute:function(b,
e){if(b&&e){if(this.hasNodeAttribute(b,e))return b;if((b=this.findNodesHavingAttribute(b,e))&&b.length)return b[0]}},findFirstNodeHavingAttributeWithValue:function(b,e){if(b&&e){if(this.hasNodeAttributeWithValue(b,e))return b;if((b=this.findNodesHavingAttribute(b,e))&&b.length){var f;for(f=0;f<b.length;f++)if(this.getAttributeValueFromNode(b[f],e))return b[f]}}},findNodesHavingCssClass:function(b,e,f){f||(f=[]);if(!b||!e)return f;if(b.getElementsByClassName)return e=b.getElementsByClassName(e),this.htmlCollectionToArray(e);
b=T(b);if(!b||!b.length)return[];var g;for(g=0;g<b.length;g++){var r=b[g];this.hasNodeCssClass(r,e)&&f.push(r);f=this.findNodesHavingCssClass(r,e,f)}return f},findFirstNodeHavingClass:function(b,e){if(b&&e){if(this.hasNodeCssClass(b,e))return b;if((b=this.findNodesHavingCssClass(b,e))&&b.length)return b[0]}},isLinkElement:function(b){if(!b)return!1;b=String(b.nodeName).toLowerCase();return-1!==M(["a","area"],b)},setAnyAttribute:function(b,e,f){b&&e&&(b.setAttribute?b.setAttribute(e,f):b[e]=f)}},I=
{CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return u.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+
"]"])},findContentNodesWithinNode:function(b){if(!b)return[];var e=u.findNodesHavingCssClass(b,this.CONTENT_CLASS),f=u.findNodesHavingAttribute(b,this.CONTENT_ATTR);if(f&&f.length){var g;for(g=0;g<f.length;g++)e.push(f[g])}u.hasNodeAttribute(b,this.CONTENT_ATTR)?e.push(b):u.hasNodeCssClass(b,this.CONTENT_CLASS)&&e.push(b);return e=u.makeNodesUnique(e)},findParentContentNode:function(b){if(b)for(var e=0;b&&b!==w&&b.parentNode;){if(u.hasNodeAttribute(b,this.CONTENT_ATTR)||u.hasNodeCssClass(b,this.CONTENT_CLASS))return b;
b=b.parentNode;if(1E3<e)break;e++}},findPieceNode:function(b){var e;(e=u.findFirstNodeHavingAttribute(b,this.CONTENT_PIECE_ATTR))||(e=u.findFirstNodeHavingClass(b,this.CONTENT_PIECE_CLASS));return e?e:b},findTargetNodeNoDefault:function(b){if(b){var e=u.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_TARGET_ATTR);if(e||(e=u.findFirstNodeHavingAttribute(b,this.CONTENT_TARGET_ATTR))||(e=u.findFirstNodeHavingClass(b,this.CONTENT_TARGET_CLASS)))return e}},findTargetNode:function(b){var e=this.findTargetNodeNoDefault(b);
return e?e:b},findContentName:function(b){if(b){var e=u.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_NAME_ATTR);if(e)return u.getAttributeValueFromNode(e,this.CONTENT_NAME_ATTR);if(e=this.findContentPiece(b))return this.removeDomainIfIsInLink(e);if(u.hasNodeAttributeWithValue(b,"title"))return u.getAttributeValueFromNode(b,"title");e=this.findPieceNode(b);if(u.hasNodeAttributeWithValue(e,"title"))return u.getAttributeValueFromNode(e,"title");b=this.findTargetNode(b);if(u.hasNodeAttributeWithValue(b,
"title"))return u.getAttributeValueFromNode(b,"title")}},findContentPiece:function(b){if(b){var e=u.findFirstNodeHavingAttributeWithValue(b,this.CONTENT_PIECE_ATTR);if(e)return u.getAttributeValueFromNode(e,this.CONTENT_PIECE_ATTR);b=this.findPieceNode(b);if(b=this.findMediaUrlInNode(b))return this.toAbsoluteUrl(b)}},findContentTarget:function(b){if(b){var e=this.findTargetNode(b);if(u.hasNodeAttributeWithValue(e,this.CONTENT_TARGET_ATTR))return u.getAttributeValueFromNode(e,this.CONTENT_TARGET_ATTR);
if(u.hasNodeAttributeWithValue(e,"href"))return b=u.getAttributeValueFromNode(e,"href"),this.toAbsoluteUrl(b);b=this.findPieceNode(b);if(u.hasNodeAttributeWithValue(b,"href"))return b=u.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(b)}},isSameDomain:function(b){if(!b||!b.indexOf)return!1;if(0===b.indexOf(this.getLocation().origin))return!0;b=b.indexOf(this.getLocation().host);return 8>=b&&0<=b?!0:!1},removeDomainIfIsInLink:function(b){b&&b.search&&-1!==b.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(b)&&
((b=b.replace(/^.*\/\/[^/]+/,""))||(b="/"));return b},findMediaUrlInNode:function(b){if(b){var e=b.nodeName.toLowerCase();if(-1!==M(["img","embed","video","audio"],e)&&u.findFirstNodeHavingAttributeWithValue(b,"src"))return b=u.findFirstNodeHavingAttributeWithValue(b,"src"),u.getAttributeValueFromNode(b,"src");if("object"===e&&u.hasNodeAttributeWithValue(b,"data"))return u.getAttributeValueFromNode(b,"data");if("object"===e){if((e=u.findNodesByTagName(b,"param"))&&e.length){var f;for(f=0;f<e.length;f++)if("movie"===
u.getAttributeValueFromNode(e[f],"name")&&u.hasNodeAttributeWithValue(e[f],"value"))return u.getAttributeValueFromNode(e[f],"value")}if((b=u.findNodesByTagName(b,"embed"))&&b.length)return this.findMediaUrlInNode(b[0])}}},trim:function(b){return b&&String(b)===b?b.replace(/^\s+|\s+$/g,""):b},isOrWasNodeInViewport:function(b){if(!b||!b.getBoundingClientRect||1!==b.nodeType)return!0;var e=b.getBoundingClientRect(),f=w.documentElement||{},g=0>e.top;g&&b.offsetTop&&(g=0<b.offsetTop+e.height);b=f.clientWidth;
x.innerWidth&&b>x.innerWidth&&(b=x.innerWidth);f=f.clientHeight;x.innerHeight&&f>x.innerHeight&&(f=x.innerHeight);return(0<e.bottom||g)&&0<e.right&&e.left<b&&(e.top<f||g)},isNodeVisible:function(b){var e=Qa(b);b=this.isOrWasNodeInViewport(b);return e&&b},buildInteractionRequestParams:function(b,e,f,g){var r="";b&&(r+="c_i="+E(b));e&&(r&&(r+="&"),r+="c_n="+E(e));f&&(r&&(r+="&"),r+="c_p="+E(f));g&&(r&&(r+="&"),r+="c_t="+E(g));return r},buildImpressionRequestParams:function(b,e,f){b="c_n="+E(b)+"&c_p="+
E(e);f&&(b+="&c_t="+E(f));return b},buildContentBlock:function(b){if(b){var e=this.findContentName(b),f=this.findContentPiece(b);b=this.findContentTarget(b);e=this.trim(e);f=this.trim(f);b=this.trim(b);return{name:e||"Unknown",piece:f||"Unknown",target:b||""}}},collectContent:function(b){if(!b||!b.length)return[];var e=[],f;for(f=0;f<b.length;f++){var g=this.buildContentBlock(b[f]);k(g)&&e.push(g)}return e},setLocation:function(b){this.location=b},getLocation:function(){var b=this.location||x.location;
b.origin||(b.origin=b.protocol+"//"+b.hostname+(b.port?":"+b.port:""));return b},toAbsoluteUrl:function(b){return b&&String(b)===b||""===b?""===b?this.getLocation().href:-1!==b.search(/^\/\//)?this.getLocation().protocol+b:-1!==b.search(/:\/\//)?b:0===b.indexOf("#")||0===b.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+b:0===b.search("^[a-zA-Z]{2,11}:")?b:-1!==b.search(/^\//)?this.getLocation().origin+b:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+b:
b},isUrlToCurrentDomain:function(b){b=this.toAbsoluteUrl(b);if(!b)return!1;var e=this.getLocation().origin;return e===b?!0:0===String(b).indexOf(e)?":"===String(b).substr(e.length,1)?!1:!0:!1},setHrefAttribute:function(b,e){b&&e&&u.setAnyAttribute(b,"href",e)},shouldIgnoreInteraction:function(b){var e=u.hasNodeAttribute(b,this.CONTENT_IGNOREINTERACTION_ATTR);b=u.hasNodeCssClass(b,this.CONTENT_IGNOREINTERACTION_CLASS);return e||b}};D(x,"beforeunload",function(){na("unload");if(Ua){do var b=new Date;
while(b.getTimeAlias()<Ua)}},!1);(function(){var b;w.addEventListener?D(w,"DOMContentLoaded",function f(){w.removeEventListener("DOMContentLoaded",f,!1);ma()}):w.attachEvent&&(w.attachEvent("onreadystatechange",function f(){"complete"===w.readyState&&(w.detachEvent("onreadystatechange",f),ma())}),w.documentElement.doScroll&&x===x.top&&function g(){if(!Sa){try{w.documentElement.doScroll("left")}catch(r){setTimeout(g,0);return}ma()}}());/WebKit/.test(fa.userAgent)&&(b=setInterval(function(){if(Sa||
/loaded|complete/.test(w.readyState))clearInterval(b),ma()},10));D(x,"load",ma,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;var db=new Nb;var Mb={setTrackerUrl:1,setAPIUrl:1,setUserId:1,setSiteId:1,disableCookies:1,enableLinkTracking:1};for(ra=0;ra<_paq.length;ra++){var pb=_paq[ra][0];Mb[pb]&&(J(_paq[ra]),delete _paq[ra],1<Mb[pb]&&void 0!==console&&console&&console.error&&console.error("The method "+pb+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'),
Mb[pb]++)}for(ra=0;ra<_paq.length;ra++)_paq[ra]&&J(_paq[ra]);_paq=new function(){return{push:J}};var wc={addPlugin:function(b,e){Ra[b]=e},getTracker:function(b,e){k(e)||(e=this.getAsyncTracker().getSiteId());k(b)||(b=this.getAsyncTracker().getTrackerUrl());return new Nb(b,e)},getAsyncTracker:function(){return db}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return wc});return wc}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();
(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
"function"!==typeof piwik_log&&(piwik_log=function(l,k,n,v){function p(D){try{return eval("piwik_"+D)}catch(na){}}var J=Piwik.getTracker(n,k);J.setDocumentTitle(l);J.setCustomData(v);(l=p("tracker_pause"))&&J.setLinkTrackingTimer(l);(l=p("download_extensions"))&&J.setDownloadExtensions(l);(l=p("hosts_alias"))&&J.setDomains(l);(l=p("ignore_classes"))&&J.setIgnoreClasses(l);J.trackPageView();p("install_tracker")&&(piwik_track=function(D,na,ma,W){J.setSiteId(na);J.setTrackerUrl(ma);J.trackLink(D,W)},
J.enableLinkTracking())});
